apiVersion: v1
kind: Service
metadata:
  name: "jenkins"
  namespace: "ci"
  labels:
    name: "jenkins"
    public: "true"
spec:
  selector:
    name: "jenkins"
  ports:
  - port: 443
    targetPort: 8080
    name: "https"
